# Generated by Django 4.1.2 on 2024-07-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionviajes', '0003_alter_paqueteturistico_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionviajes.carrito')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionviajes.paqueteturistico')),
            ],
        ),
        migrations.AlterField(
            model_name='carrito',
            name='paquetes',
            field=models.ManyToManyField(through='gestionviajes.CarritoPaquete', to='gestionviajes.paqueteturistico'),
        ),
    ]
