# Generated by Django 4.1.2 on 2024-07-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionviajes', '0004_carritopaquete_alter_carrito_paquetes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='paquetes',
        ),
    ]
