# Generated by Django 4.1.2 on 2024-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionviajes', '0005_remove_carrito_paquetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='paquetes',
            field=models.ManyToManyField(through='gestionviajes.CarritoPaquete', to='gestionviajes.paqueteturistico'),
        ),
    ]
